import { Command } from '../types/bot';
import { GoogleGenAI } from '@google/genai';

let aiInstance: GoogleGenAI | null = null;

function getGeminiClient(): GoogleGenAI {
  if (!aiInstance) {
    const key = process.env.GEMINI_API_KEY;
    if (!key) {
      throw new Error(
        'GEMINI_API_KEY environment variable is missing. Please set your Gemini API key in the Settings > Secrets segment of the AI Studio control dashboard.'
      );
    }
    aiInstance = new GoogleGenAI({
      apiKey: key,
      httpOptions: {
        headers: {
          'User-Agent': 'aistudio-build',
        },
      },
    });
  }
  return aiInstance;
}

const aiCommands: Command[] = [
  {
    name: 'ai',
    description: 'Query the server-side Gemini model for intelligent suggestions',
    category: 'AI',
    aliases: ['ask', 'chatgpt'],
    execute: async ({ reply, args, senderName }) => {
      const prompt = args.join(' ');
      if (!prompt) {
        await reply('❌ *Prompt required:* Please enter a query after this command.\nExample: `.ai Explain quantum computing simply.`');
        return;
      }

      await reply('🧠 *Gemini AI Gateway:* Processing network vectors...');

      try {
        const ai = getGeminiClient();
        const response = await ai.models.generateContent({
          model: 'gemini-3.5-flash',
          contents: prompt,
          config: {
            systemInstruction: 'You are BUGGU MD, a highly intelligent, premium, and friendly WhatsApp companion bot developed by Divyansh Deewana. Keep your answers clear, concise, and visually elegant. Use emojis sparingly but appropriately.',
          }
        });

        const answer = response.text || '⚠️ No response text was generated by Gemini.';
        await reply(`✨ *BUGGU MD AI PORTAL*\n\n👤 *User:* ${senderName}\n🧠 *Response:*\n${answer}\n\n_Generated via Google Gemini 3.5 Flash._`);
      } catch (err: any) {
        await reply(`❌ *AI Engine Exception:* ${err.message || String(err)}`);
      }
    }
  },
  {
    name: 'image',
    description: 'Generate high-quality AI artwork based on descriptive prompt text input',
    category: 'AI',
    aliases: ['img', 'generate'],
    execute: async ({ reply, args, sock, remoteJid, msg }) => {
      const prompt = args.join(' ');
      if (!prompt) {
        await reply('❌ *Error:* Please enter an image description/prompt.\nExample: `.image A majestic cat wearing a king crown, neon cyberpunk background`');
        return;
      }

      await reply('🎨 *Image Generator Engaged:* Synthesizing canvas graphics. This takes raw processing power, please hold...');

      try {
        const ai = getGeminiClient();
        const response = await ai.models.generateContent({
          model: 'gemini-2.5-flash-image',
          contents: prompt,
        });

        let imageBuffer: Buffer | null = null;
        if (response.candidates?.[0]?.content?.parts) {
          for (const part of response.candidates[0].content.parts) {
            if (part.inlineData?.data) {
              imageBuffer = Buffer.from(part.inlineData.data, 'base64');
              break;
            }
          }
        }

        if (imageBuffer) {
          await sock.sendMessage(remoteJid, {
            image: imageBuffer,
            caption: `🎨 *AI Canvas Rendering Concluded!* ✨\n\n📝 *Prompt:* "${prompt}"\n🧠 *Render Engine:* Gemini-Image-Generators`
          }, { quoted: msg as any });
        } else {
          await reply('❌ *Generation Fault:* Models did not return valid image payload. Please verify your prompt structure and try again.');
        }
      } catch (err: any) {
        await reply(`❌ *AI Canvas Error:* ${err.message || String(err)}`);
      }
    }
  },
  {
    name: 'code',
    description: 'Generate production-ready code blocks and code solutions',
    category: 'AI',
    execute: async ({ reply, args }) => {
      const prompt = args.join(' ');
      if (!prompt) {
        await reply('❌ *Usage:* Provide coding details.\nExample: `.code bubble sort in go`');
        return;
      }

      await reply('💻 *Code generation in progress:* Consulting compile vectors...');

      try {
        const ai = getGeminiClient();
        const response = await ai.models.generateContent({
          model: 'gemini-3.1-pro-preview', // high reasoning coding model
          contents: `Generate clean, robust code for: ${prompt}. Only return code block and extremely brief description.`,
        });

        await reply(`💻 *BUGGU MD SYNTAX RESOLVER*\n\n${response.text}`);
      } catch (err: any) {
        await reply(`❌ *Compile Gateway Error:* ${err.message || String(err)}`);
      }
    }
  },
  {
    name: 'translate',
    description: 'Translate text from one language to another using AI precision',
    category: 'AI',
    execute: async ({ reply, args }) => {
      const text = args.join(' ');
      if (!text) {
        await reply('❌ *Usage:* Provide target language and text to translate.\nExample: `.translate French Hello how are you today?`');
        return;
      }

      await reply('🌐 *Universal Translator active:* Recalibrating linguistics...');

      try {
        const ai = getGeminiClient();
        const response = await ai.models.generateContent({
          model: 'gemini-3.5-flash',
          contents: `Translate the following text exactly according to description. Only return the translated text without extra text: ${text}`,
        });

        await reply(`🌐 *BUGGU MD MULTILINGUAL TRANSLATION*\n\n${response.text}`);
      } catch (err: any) {
        await reply(`❌ *Translator Error:* ${err.message || String(err)}`);
      }
    }
  },
  {
    name: 'summarize',
    description: 'Condense logs, lengthy text sheets, or scripts into structured reports',
    category: 'AI',
    execute: async ({ reply, args }) => {
      const text = args.join(' ');
      if (!text) {
        await reply('❌ *Usage:* Reply to a lengthy message or specify the paragraphs to summarize.');
        return;
      }

      await reply('📝 *Content Condenser:* Reading paragraphs...');

      try {
        const ai = getGeminiClient();
        const response = await ai.models.generateContent({
          model: 'gemini-3.5-flash',
          contents: `Provide a bulleted list summary of this text:\n\n${text}`,
        });

        await reply(`📝 *BUGGU MD CONCISE REPORT EXECUTIVE SUMMARY*\n\n${response.text}`);
      } catch (err: any) {
        await reply(`❌ *Summarizer Error:* ${err.message || String(err)}`);
      }
    }
  }
];

export default aiCommands;
